services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      OSRM_CAR_URL: http://osrm-car:5000
      OSRM_BIKE_URL: http://osrm-bike:5001
      OSRM_FOOT_URL: http://osrm-foot:5002
      TRAFFIC_CSV_PATH: /traffic/traffic.csv
      OSRM_DATA_DIR: /data
      DOCKER_ENV: "1"
    volumes:
      - ./backend:/app
      - ./osrm-data/car:/traffic
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  osrm-car:
    image: osrm/osrm-backend:latest
    ports:
      - "5000:5000"
    volumes:
      - ./osrm-data/car:/data
    command: >
      sh -c "
      if [ ! -f /data/.extracted ]; then
        osrm-extract -p /opt/car.lua /data/uralsky-federal-district-latest.osm.pbf &&
        osrm-partition /data/uralsky-federal-district-latest.osrm &&
        touch /data/.extracted ;
      fi ;
      if [ -f /data/traffic.csv ]; then
        osrm-customize /data/uralsky-federal-district-latest.osrm --segment-speed-file /data/traffic.csv ;
      else
        osrm-customize /data/uralsky-federal-district-latest.osrm ;
      fi ;
      osrm-routed --algorithm mld --ip 0.0.0.0 --port 5000 /data/uralsky-federal-district-latest.osrm
      "
    restart: unless-stopped

  osrm-bike:
    image: osrm/osrm-backend:latest
    ports:
      - "5001:5001"
    volumes:
      - ./osrm-data/bike:/data
    command: >
      sh -c "
      if [ ! -f /data/bike.osrm ]; then
        osrm-extract -p /opt/bicycle.lua /data/uralsky-federal-district-latest.osm.pbf &&
        osrm-partition /data/uralsky-federal-district-latest.osrm &&
        osrm-customize /data/uralsky-federal-district-latest.osrm &&
        mv /data/uralsky-federal-district-latest.osrm /data/bike.osrm
      fi &&
      osrm-routed --algorithm mld --ip 0.0.0.0 --port 5001 /data/bike.osrm
      "
    restart: unless-stopped

  osrm-foot:
    image: osrm/osrm-backend:latest
    ports:
      - "5002:5002"
    volumes:
      - ./osrm-data/foot:/data
    command: >
      sh -c "
      if [ ! -f /data/foot.osrm ]; then
        osrm-extract -p /opt/foot.lua /data/uralsky-federal-district-latest.osm.pbf &&
        osrm-partition /data/uralsky-federal-district-latest.osrm &&
        osrm-customize /data/uralsky-federal-district-latest.osrm &&
        mv /data/uralsky-federal-district-latest.osrm /data/foot.osrm
      fi &&
      osrm-routed --algorithm mld --ip 0.0.0.0 --port 5002 /data/foot.osrm
      "
    restart: unless-stopped
