name: Deploy to Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd /home/developer/delivery-optimizer
            git fetch --all
            git reset --hard origin/master
            
            # Деплой бэкенда
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            
            # Деплой фронтенда
            cd frontend
            npm install
            npm run build
            
            # Перезапуск nginx
            sudo systemctl restart nginx
